apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-bus
  name: new-env-app-bus
  namespace: openshift-gitops
spec:
  destination:
    namespace: new-env
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/new-env/apps/app-bus/overlays
    repoURL: https://github.com/varshab1210/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
